### ISSUE TITLE
Cannot find module `../modules/settings.js`

### ISSUE THREAD

**Issue by mzch** [cyborg00222/filedrop#1]
I tried to set up filedrop but it didn't start because of the following error:

```
Feb  8 19:43:24 lo nodejs-filedrop[3330]: internal/modules/cjs/loader.js:638
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     throw err;
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     ^
Feb  8 19:43:24 lo nodejs-filedrop[3330]: Error: Cannot find module '../modules/settings.js'
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at require (internal/modules/cjs/helpers.js:25:18)
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at Object.<anonymous> (/srv/filedrop/filedrop/app.js:8:16)
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Feb  8 19:43:24 lo nodejs-filedrop[3330]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

There exists `modules/settings.js`. How can I fix this issue?

EDITED: `node.js` : `v10.19.0`

**Comment by cyboerg42** [comment]
Hi! Sorry for the late answer, i guess it was a failure on my side. Can you try it with the change which i've pushed into the repo a sec ago?

**Comment by cyboerg42** [comment]
related to -> https://github.com/cyboerg42/filedrop/commit/aff80080d89ca91dee0d91cda16b5c5610eaa921

**Comment by mzch** [comment]
HI, an error occurred as below:

```
Apr 24 19:43:29 lo nodejs-filedrop[3913]: internal/modules/cjs/loader.js:638
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     throw err;
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     ^
Apr 24 19:43:29 lo nodejs-filedrop[3913]: Error: Cannot find module 'uuid-random'
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at require (internal/modules/cjs/helpers.js:25:18)
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at Object.<anonymous> (/srv/filedrop/filedrop/routes/upload.js:7:14)
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Apr 24 19:43:29 lo nodejs-filedrop[3913]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Apr 24 19:43:29 lo systemd[1]: filedrop.service: Main process exited, code=exited, status=1/FAILURE
Apr 24 19:43:29 lo systemd[1]: filedrop.service: Failed with result 'exit-code'.
Apr 24 19:43:40 lo systemd[1]: filedrop.service: Service RestartSec=10s expired, scheduling restart.
Apr 24 19:43:40 lo systemd[1]: filedrop.service: Scheduled restart job, restart counter is at 2.
Apr 24 19:43:40 lo systemd[1]: Stopped filedrop.
Apr 24 19:43:40 lo systemd[1]: Started filedrop.
Apr 24 19:43:40 lo nodejs-filedrop[3953]: internal/modules/cjs/loader.js:638
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     throw err;
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     ^
Apr 24 19:43:40 lo nodejs-filedrop[3953]: Error: Cannot find module 'uuid-random'
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at require (internal/modules/cjs/helpers.js:25:18)
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at Object.<anonymous> (/srv/filedrop/filedrop/routes/upload.js:7:14)
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Apr 24 19:43:40 lo nodejs-filedrop[3953]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Apr 24 19:43:40 lo systemd[1]: filedrop.service: Main process exited, code=exited, status=1/FAILURE
Apr 24 19:43:40 lo systemd[1]: filedrop.service: Failed with result 'exit-code'.
Apr 24 19:43:44 lo npm[702]: ip: 5.189.141.124      req url: http://xchtube.com/media/recent/7?media=all&category=gaming&page=    header: undefined
Apr 24 19:43:44 lo npm[702]: #033[0mGET /media/recent/7?media=all&category=gaming&page= #033[32m200 #033[0m8.637 ms - -#033[0m
```
And I did `npm install uuid-random`, then filedrop works fine! :)

**Comment by cyboerg42** [comment]
awesome, thanks for testing!

Maybe I'll tidy it up a bit in a few days, as the code is just laying around since 2 years.. I bet I can do the same thing without depending on uuid-random.

have a nice day, and have fun with filedrop! :)
